project:
  type: website
  output-dir: docs  

website:
  title: "Rithvik Madhavaram"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Education.qmd
      - Hobbies.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true



